zeroconf: Autospec creation for update from version 0.28.4 to version 0.28.5
J. Nick Koston (1):
      Ignore duplicate messages (#299)

Jakub Stasiak (3):
      Test with the development version of Python 3.9 (#300)
      Fix AttributeError: module 'unittest' has no attribute 'mock' (#302)
      Release version 0.28.5